services:
  db:
    image: postgres:13
    container_name: db
    restart: always
    env_file: ./.env
    ports:
      - 5332:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
  
  minio:
    image: minio/minio
    container_name: minio
    restart: unless-stopped
    ports:
      - 9010:9000
      - 9011:9001
    expose:
      - "9000"
    volumes:
      - minio_storage:/data
    environment:
      - MINIO_ROOT_USER=miniouser
      - MINIO_ROOT_PASSWORD=admin123
    command: server /data --console-address ":9001"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
    # profiles:
    #   - donotstart

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: zookeeperr
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafkaa
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    volumes:
      - kafka_data:/var/lib/kafka/data
    healthcheck:
      test: /bin/kafka-topics --bootstrap-server localhost:9092 --list | grep -E 'notifications' &> /dev/null
      start_period: 60s
      interval: 10s
      timeout: 5s
      retries: 5

  init-kafka:
    image: confluentinc/cp-kafka:7.6.0
    depends_on:
      - kafka
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "
      # blocks until kafka is reachable
      kafka-topics --bootstrap-server kafka:9092 --list

      echo -e 'Creating kafka topics'
      kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic notifications --replication-factor 1 --partitions 1

      echo -e 'Successfully created the following topics:'
      kafka-topics --bootstrap-server kafka:9092 --list"

  gateway:
    build:
      context: .
      dockerfile: Gateway/Dockerfile
    container_name: gateway
    ports:
      - "5000:8080"
    depends_on:
      - db
      - kafka
      - minio
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Kafka__BootstrapServers=kafka:9092
      - Kafka__GroupId=gateway-sender
      - Kafka__Topics__Sms=notifications.sms
      - Kafka__Topics__Email=notifications.email
      - Kafka__Topics__Push=notifications.push
      - Kafka__Topics__Messenger=notifications.messenger
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=myapp;Username=postgres;Password=password
    volumes:
      - ./Gateway/appsettings.json:/app/appsettings.json
      - ./Gateway/appsettings.Development.json:/app/appsettings.Development.json

  emailsender:
    build:
      context: .
      dockerfile: EmailSender/Dockerfile
    container_name: emailsender
    ports:
      - "5001:8080"
    depends_on:
      - db
      - kafka
      - minio
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Kafka__BootstrapServers=kafka:9092
      - Kafka__GroupId=email-sender
      - Kafka__Topic=notifications.email
      - Kafka__MaxParallel=8
      - Kafka__EnableAutoCommit=true
      - Kafka__AutoOffsetReset=Earliest
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=myapp;Username=postgres;Password=password
      - EmailSettings__SmtpHost=smtp.gmail.com
      - EmailSettings__SmtpPort=587
      - EmailSettings__UseSsl=true
      - EmailSettings__SmtpUser=mock_user
      - EmailSettings__SmtpPassword=mock_password

  smssender:
    build:
      context: .
      dockerfile: SmsSender/Dockerfile
    container_name: smssender
    ports:
      - "5002:8080"
    depends_on:
      - db
      - kafka
      - minio
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Kafka__BootstrapServers=kafka:9092
      - Kafka__GroupId=sms-sender
      - Kafka__Topic=notifications.sms
      - Kafka__MaxParallel=8
      - Kafka__EnableAutoCommit=true
      - Kafka__AutoOffsetReset=Earliest
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=myapp;Username=postgres;Password=password
      - SmsSettings__Provider=Mock
      - SmsSettings__UseMock=true
      - SmsSettings__Twilio__AccountSid=
      - SmsSettings__Twilio__AuthToken=
      - SmsSettings__Twilio__FromNumber=
      - SmsSettings__AwsSns__Region=eu-west-1
      - SmsSettings__AwsSns__AccessKeyId=
      - SmsSettings__AwsSns__SecretAccessKey=
      - SmsSettings__AwsSns__SenderId=
    volumes:
      - ./SmsSender/appsettings.json:/app/appsettings.json
      - ./SmsSender/appsettings.Development.json:/app/appsettings.Development.json

  pushsender:
    build:
      context: .
      dockerfile: PushSender/Dockerfile
    container_name: pushsender
    ports:
      - "5003:8080"
    depends_on:
      - db
      - kafka
      - minio
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

      - Kafka__BootstrapServers=kafka:9092
      - Kafka__GroupId=push-sender
      - Kafka__Topic=notifications.push
      - Kafka__MaxParallel=8
      - Kafka__EnableAutoCommit=true
      - Kafka__AutoOffsetReset=Earliest

      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=myapp;Username=postgres;Password=password

      - FirebaseSettings__UseMock=false
      - FirebaseSettings__CredentialsPath=firebase-credentials.json
      - FirebaseSettings__AppName=PushSender
    
    volumes:
      - ./PushSender/appsettings.json:/app/appsettings.json
      - ./PushSender/appsettings.Development.json:/app/appsettings.Development.json

  messengersender:
    build:
      context: .
      dockerfile: MessengerSender/Dockerfile
    container_name: messengersender
    ports:
      - "5004:8080"
    depends_on:
      - db
      - kafka
      - minio
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    
      - Kafka__BootstrapServers=kafka:9092
      - Kafka__GroupId=messenger-sender
      - Kafka__Topic=notifications.messenger
      - Kafka__MaxParallel=8
      - Kafka__EnableAutoCommit=true
      - Kafka__AutoOffsetReset=Earliest
    
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=myapp;Username=postgres;Password=password
    
      - MessengerSettings__Provider=Mock
    
      - MessengerSettings__Telegram__BotToken=
      - MessengerSettings__WhatsApp__AccessToken=
      - MessengerSettings__WhatsApp__PhoneNumberId=
      - MessengerSettings__WhatsApp__TemplateName=
      - MessengerSettings__WhatsApp__LanguageCode=en_US
    volumes:
      - ./MessengerSender/appsettings.json:/app/appsettings.json
      - ./MessengerSender/appsettings.Development.json:/app/appsettings.Development.json

volumes:
  pg_data:
  minio_storage:
  kafka_data: